name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: install ssh
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts

      - name: connect and deploy
        run: |
          ssh "${{ secrets.USERNAME }}@${{ secrets.HOST }}" "
            cd ${{ secrets.SITE_PATH }} &&
            git switch -f master &&
            git pull &&
            docker compose -p mowoji -f docker-compose.yml up -d --build &&
            cd frontend &&
            rm -rf node_modules &&
            bun i &&
            bun run build
          "

      - name: cleanup
        run: rm -rf ~/.ssh
